config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  match '/about', to: 'static_pages#about', via: 'get'

  resources :sessions, only:[:new, :create, :destroy]
  resources :users, except: [:index]  do
    resources :videos, only: [:index, :new, :create, :destroy]
    resources :playlists, except: [:edit]
    resources :events
  end

  post 'playlists/new', to: 'playlists#create'

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :user
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @videos = Video.order('created_at DESC')
  end

  def new
    @user = User.find(params[:user_id])
    @video = Video.new
  end

  def create
    @user = User.find(params[:user_id])
    @video = Video.new(video_params)
    if @video.save
      flash[:success] = 'Video added!'
      redirect_to user_videos_path
    else
      render :new
    end
  end

  def destroy
    @video = Video.find(params[:id])
    @video.destroy
    redirect_to user_videos_path, notice: 'Video deleted'
  end


  private

  def video_params
    params.require(:video).permit(:link)
  end
end

app/views/videos/index.html.erb
<div class="container">
  <h1>View your favorite vids here</h1>
  <p>Click the button below to share your video from YouTube.</p>
  <p>
    <%= link_to 'Add video now!', new_user_video_path, class: 'btn waves-effect waves-light' %>
  </p>
</div>


<% if @videos.any? %>
  <div class="container">
    <h1>Latest videos</h1>
    <div id="player-wrapper"></div>
    <% @videos.in_groups_of(3) do |group| %>
      <div class="row">
        <% group.each do |video| %>
          <% if video %>
            <div class="col s12 m6">
              <div class="yt_video thumbnail">
                <iframe id="player" type="text/html" width="300" height="200"
                    src="https://www.youtube.com/embed/<%= video.uid %>"
                    frameborder="0" allowfullscreen></iframe>
                <div class="caption">
                  <h5><%= video.title %></h5>
                  <% if video.published_at %>
                    <p>Published at <%= video.published_at.strftime('%-d %B %Y %H:%M:%S') %></p>
                  <% end %>
                  <p>
                    <span> <i class="mdi-action-thumb-up"> 👍</i></span> <%= video.likes %> <span> </span>
                    <span> <i class="mdi-action-thumb-up"> 👎</i></span> <%= video.dislikes %>
                  </p>
                  <i class="mdi-action-delete"><%= link_to "Delete", user_video_path(@user,video) , method: :delete, data: { confirm: 'Are you certain?' } %></i>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/videos/new.html.erb
<div class="container">
  <h1>New video</h1>

  <%= form_for [@user, @video] do |f| %>
    <div class="form-group">
      <%= f.label :link %>
      <%= f.text_field :link, class: 'form-control', required: true %>
      <span class="help-block">A link to the video on YouTube.</span>
    </div>

    <%= f.submit class: 'btn waves-effect waves-light' %>
  <% end %>
</div>