config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  match '/about', to: 'static_pages#about', via: 'get'

  resources :sessions, only:[:new, :create, :destroy]
  resources :users, except: [:index]  do
    resources :videos, only: [:index, :new, :create, :destroy]
    resources :playlists, except: [:edit]
    resources :events
  end

  post 'playlists/new', to: 'playlists#create'

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/models/event.rb
class Event < ActiveRecord::Base  
  belongs_to :user
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @user = User.find(params[:user_id])
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @user = User.find(params[:user_id])
    @event = Event.find(params[:id])
  end

  # GET /events/new
  def new
    @user = User.find(params[:user_id])
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    @user = User.find(params[:user_id])
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @user = User.find(params[:user_id])
    @event = @user.events.create(event_params.merge(user: current_user))
    redirect_to user_events_path
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    @user = User.find(params[:user_id])
    @event = Event.find(params[:id])
    @event.update(event_params.merge(user:current_user))
    redirect_to user_path(@event)
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @user = User.find(params[:user_id])
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to user_events_path(@user)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :link, :start_time)
    end
end

app/views/events/_calendar.html.erb
<%= month_calendar events: @events do |date, events| %>
  <%= date.strftime("%d") %>

  <% events.each do |event| %>
    <div>
      <%= event.name %>
    </div>
  <% end %>
<% end %>

app/views/events/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col s12">
      <div class="card playlist-text black-text darken-1">
        <%= form_for [@user, @event] do |f| %>
          <% if @event.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>
              <ul>
              <% @event.errors.full_messages.each do |event| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
        <div class="field">
          <%= f.label :name %><br>
          <%= f.text_field :name %>
        </div>
        <div class="field">
          <%= f.label :start_time %><br>
          <%= f.datetime_select :start_time %>
        </div>
        <div class="field">
          <%= f.label :description %><br>
          <%= f.text_area :description %>
        </div>
        <div class="field">
          <%= f.label :link %><br>
          <%= f.text_field :link %>
        </div>
        <div class="field">
          <%= button_tag(type: "submit", class: "btn waves-effect waves-light") do %>
                <i class="mdi-social-person-add"> New Event</i>
                <% end %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/edit.html.erb
<h1>Editing Events</h1>

<p> change of plans</p>

<%= render 'form' %>

<%= link_to 'Show', user_event_path(@user, @event), class: "btn waves-effect waves-light" %>
<%= link_to 'Back', user_events_path, class: "btn waves-effect waves-light" %>

app/views/events/index.html.erb
<div class="mid-section">
  <p id="notice"><%= notice %></p>
  <% if current_user%>
  <h1>Event Schedule</h1>
  <div id="events_calendar">
    <%= render :partial => "calendar", locals: {events: @events} %>
  </div>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Start time</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td><%= event.name %></td>
          <td><%= event.start_time.strftime("%Y-%m-%d %l:%M %p") %></td>
          <td><%= link_to 'Show', user_event_path(@user,event), class: "btn waves-effect waves-light" %></td>
          <td><%= link_to 'Edit', edit_user_event_path(@user, event), class: "btn waves-effect waves-light" %></td>
          <td><%= link_to 'Destroy', user_event_path(@user, event), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn waves-effect waves-light" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to 'New Event', new_user_event_path, class: "btn waves-effect waves-light" %>
  <%end%>
</div>

app/views/events/new.html.erb
<h1>Event</h1>

<%= render 'form' %>

<%= link_to 'Back', user_events_path, class: "btn waves-effect waves-light" %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @event.start_time %>
</p>

<p>
<strong>Details</strong> <br>
<%= @event.description %>
</p>

<div class = "btn waves-effect waves-light">
<p>
<strong>Link </strong> <br>
<a href="<%= @event.link %>"><%= @event.name %></a>
</p>
</div>

<% if current_user %>
<%= link_to 'Edit', edit_user_event_path(@user, @event), class: "btn waves-effect waves-light" %>
<%= link_to 'Back', user_events_path, class: "btn waves-effect waves-light" %>
<%end%>