config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  match '/about', to: 'static_pages#about', via: 'get'

  resources :sessions, only:[:new, :create, :destroy]
  resources :users, except: [:index]  do
    resources :videos, only: [:index, :new, :create, :destroy]
    resources :playlists, except: [:edit]
    resources :events
  end

  post 'playlists/new', to: 'playlists#create'

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
belongs_to :user
require 'soundcloud'

  def self.soundcloud_api_search(user_playlist_input)
    if user_playlist_input != nil
      random_playlist_id = rand(0..9)
      client = Soundcloud.new(:client_id => '13ac87726f10f3cd25a2299040d3fa7c')
      playlist = client.get('/tracks', :q => user_playlist_input, :limit => 9)
      {
        soundcloud_id:  playlist[random_playlist_id ]["id"],
        name:           playlist[random_playlist_id ]["title"]
      }
    end
  end


end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
before_action :signed_in_user
before_action :find_user
before_action :find_playlist, only: [:show, :destroy]

require 'soundcloud'

  def new
    # @playlists = Playlist.all
     if params[:playlist_user_input] != nil
      @playlist = Playlist.soundcloud_api_search(params[:playlist_user_input])
      # @playlist = Playlist.new(soundcloud_id)
     end
  end

  def index
    @playlists = Playlist.where(user_id: @user.id)
  end

  def show
  end

  def create
    @playlist = Playlist.new(playlist_params)
    @playlist.user = current_user
    @playlist.save
    redirect_to user_playlists_path
  end

  def destroy
    @playlist.destroy
    redirect_to user_playlists_path, notice: 'Playlist deleted'
  end


  private

    def playlist_params
      params.require(:playlist).permit(:soundcloud_id, :name, :user_id)
    end

    def find_user
      @user = current_user
    end

    def find_playlist
      @playlist = Playlist.find(params[:id])
    end

end

app/views/playlists/index.html.erb
<br><br><br>
    <div class="container">
        <div class="">
          <div class="card playlist-text lighten-4">
            <div class="card-content black-text">
              <span class="card-title black-text"><h4>My Playlists</h4></span>
              <% @playlists.each do |playlist| %>
  <li><%= link_to playlist.name, user_playlist_path(@user,playlist), class: "collection-item" %><span class="badge">
  <i class="mdi-action-delete"><%= link_to "Delete", user_playlist_path(@user,playlist) , method: :delete, data: { confirm: 'Are you certain?' } %></i></li>
  </span>
  </ul>
  <% end %>
            </div>
            <div class="card-action">

            </div>
          </div>
        </div>
      </div>

app/views/playlists/new.html.erb
<div class="container">
<div class="row">
  <h4 class="header center teal-text text-lighten-2">To search for a playlist enter a genre or artist </h4><br><br>
</div>

      <div class="row">
        <div class="col s12">
          <div class="card playlist-text darken-1">
            <div class="card-content white-text">
              <span class="card-title">
              <%= form_tag new_user_playlist_path, :method => 'get' do %>
              <%= text_field_tag :playlist_user_input, params[:playlist_user_input] %>
               <%= button_tag(type: "submit", class: "btn waves-effect waves-light") do %>
              <i class="mdi-action-search"> Search</i>
              <% end %>
              <% end %>
        </span>
        <% if @playlist != nil && params[:playlist_user_input] != nil%>
               <iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/<%=@playlist[:soundcloud_id]%>&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>
            </div>
            <div class="card-action">



        <%= form_tag({controller: "playlists", action: "create"}, method: "post") do %>
              <%= hidden_field_tag  "playlist[soundcloud_id]", @playlist[:soundcloud_id] %>
              <%= hidden_field_tag  "playlist[name]", @playlist[:name] %>

               <%= button_tag(type: "submit", class: "btn waves-effect waves-light") do %>
              <i class="mdi-content-save"> Save</i>
              <% end %>
             <% end %>
          <% end %>
            </div>
          </div>
        </div>
      </div>
</div>

app/views/playlists/show.html.erb
<div class="container">
       <div class="col">
         <div class="card playlist-text darken-1">
           <div class="card-content white-text">
             <span class="card-title"><%=  @playlist.name %></span>
             <iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/<%=@playlist[:soundcloud_id]%>&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>

           </div>
           <div class="card-action">
           </div>
         </div>
       </div>
     </div>