config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  match '/about', to: 'static_pages#about', via: 'get'

  resources :sessions, only:[:new, :create, :destroy]
  resources :users, except: [:index]  do
    resources :videos, only: [:index, :new, :create, :destroy]
    resources :playlists, except: [:edit]
    resources :events
  end

  post 'playlists/new', to: 'playlists#create'

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/views/layouts/_nav.html.erb
<nav class="top-nav">
  <a href="#" data-activates="slide-out" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
  <ul id="slide-out" class="side-nav fixed">
    <li> <%= render 'layouts/nav_layout' %> </li>
  </ul>
</nav>

app/views/layouts/_nav_layout.html.erb
<% if signed_in? %>
  <li><%= link_to 'New Video', new_user_video_path(@current_user) %></li>
  <li><%= link_to 'Playlist Search', new_user_playlist_path(@current_user) %> </li>
  <li><%= link_to 'My Events', user_events_path(@current_user) %> </li>
  <li><%= link_to 'My Profile', user_path(@current_user) %></li>
  <li><%= link_to 'My Videos', user_videos_path(@current_user) %></li>
  <li><%= link_to 'My Playlists', user_playlists_path(@current_user) %></li>
  <li><%= link_to 'Sign out', signout_path, method: 'delete' %></li>

<% else %>
  <li><%= link_to 'Sign up', signup_path %></li>
  <li><%= link_to 'Sign in', signin_path %></li>
  <li><%= link_to 'Home', root_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CreativeStyles</title>
  <%= stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <%= render 'layouts/nav' unless @disable_nav %>
  </header>

<%= yield %>

</body>
</html>